### ISSUE TITLE
Wrong URL for get the token

### ISSUE THREAD

**Issue by CharithaRatnayake** [VictorZhang2014/free-google-translate#1]
I have implemented the Android code. So after translate it getting some errors. Once I go through the code I found out that there is a method to  get the token from `getTKK` method. It's concat wrong url to the search query. Could you check the code.

```
public String getTKK(String q) {
        try {
            String tkkUrl = "http://xxx" + q;
            String req = sendGet(tkkUrl);
            tkk = new JSONObject(req).getString("token");
        } catch (Exception e) {
            Log.e(TAG, "=====update_TKK======" + e.toString());
        }
        return tkk;
}
```

**Comment by VictorZhang2014** [comment]
In fact, you have to access the right full api url which is `http://api.yooul.net/api/google/token?text=hello&tkk=434674.96463358`, the tkk parameter should be replaced each time you request, the value you replaced is the returned value `token`. 

Due to the url `http://api.yooul.net/` is our production api domain, please do not hack or crack it, thank you.

I'm able to tell you what the api url works, it's only implementing the `https://github.com/VictorZhang2014/free-google-translate/blob/master/Python/token.js` script on server side, you can also implement it on your PHP or Java or NodeJS or Go program, etc. on your server side.

**Comment by CharithaRatnayake** [comment]
@VictorZhang2014 Got it. Thanks mate.
